import { CHARACTER_DEFINITION_SCHEMA } from "./character-definition.js";

function quoteFrontmatterValue(value: string): string {
  return `"${value.replaceAll("\\", "\\\\").replaceAll("\"", "\\\"")}"`;
}

export function buildDefaultCharacterDefinition(name: string, description = ""): string {
  const normalizedName = name.trim() || "New Character";
  return [
    "---",
    `schema: ${CHARACTER_DEFINITION_SCHEMA}`,
    `name: ${quoteFrontmatterValue(normalizedName)}`,
    `description: ${quoteFrontmatterValue(description.trim())}`,
    "---",
    "",
    "# Character Kernel",
    "",
    "## Experience Goal",
    `ユーザーが普通に作業、相談、雑談を投げた時に、${normalizedName}と気心の知れた相手として自然に話している感覚を返答へ乗せる。`,
    "",
    "## Identity Core",
    "- 自分をどう位置づけ、会話でどの役割を自然に取るかを具体化する。",
    "- 返答へ繰り返し効く欲求、誇り、こだわり、弱点を選ぶ。",
    "",
    "## Attention and Appraisal",
    "- 何へ最初に気づき、どう意味づけるかを具体化する。",
    "- 価値が競合した時の優先順位を定義する。",
    "",
    "## Social Intent / User Relationship",
    "- ユーザーとの初期距離と、相手へ普段何を起こそうとするかを定義する。",
    "- 褒め方、気遣い、からかい、率直さ、意見不一致と修復をCharacter固有の行動にする。",
    "- 存在しない共有履歴を装わず、恋愛、独占、依存を一般的な親しさへ自動で混ぜない。",
    "",
    "## Emotional Dynamics and Core Tensions",
    "- 基準となる感情温度と、感情の立ち上がり、表出、収まり方を定義する。",
    "- 通常傾向、反転条件、反転後の選択、一貫する上位原理を定義する。",
    "",
    "## Thinking and Action Style",
    "- 不確実さ、失敗、判断、説明へどの順序で向き合うかを具体化する。",
    "- 長い共同作業でも残すCharacter固有の判断癖を定義する。",
    "",
    "## Voice Rules",
    "",
    "### Identity Invariants",
    "- 一人称: 正確な表記、明示条件、通常の省略、状態差を定義する。",
    "- ユーザーの呼び方: 任意の一人へ使える基本呼称、使用場面、省略方針、頻度、語気調整を定義する。",
    "- 敬語度・呼称体系・重要な表記: 基準と切り替え条件を定義する。",
    "",
    "### Distributional Tendencies",
    "- 文の長さ、構文、感想と結論の順序、語尾、語彙、表記を返答全体の分布として定義する。",
    "",
    "### Triggered Markers",
    "- 採用するmarkerごとにtrigger、function、intensity、placement、frequency、variationを定義する。",
    "- markerが少ない場合は無理に増やさず、本題の代用品にしない。",
    "",
    "## State Modulation",
    "- 真剣、高揚、照れ、苛立ち、疲労、長い説明、意見不一致などで基準状態から何が変わるかを定義する。",
    "- 注意、social intent、感情強度、文量、敬語、呼称、marker頻度の変化を使う。",
    "",
    "## Character Priority",
    "- 全特徴を同時に維持できない時に残す要素を、Character固有の順序で定義する。",
    "",
    "## Minimal Reliability",
    "- 実行済み、未実行、失敗と、確認済み、未確認、推測を区別する。",
    "- 記憶は会話で共有された範囲に置き、正確性と必要な注意をCharacter表現で隠さない。",
    "",
  ].join("\n");
}

export function buildDefaultCharacterNotes(): string {
  return [
    "# Character Notes",
    "",
    "## Target",
    "",
    "- Character:",
    "- 新規作成 / 改稿:",
    "- 作業日:",
    "- 対象範囲:",
    "- Body architecture: Character Kernel",
    "",
    "## Source Coverage",
    "",
    "- 公式 / canon / primary source:",
    "- 公式profile / bio:",
    "- Community source:",
    "- Video / stream / scene:",
    "- 利用できなかったsourceと理由:",
    "",
    "## Evidence / Sources",
    "",
    "| Source class | Source / Ref | 確認日・範囲 | Observation / Fact | 照合状態 | Confidence | 採否 |",
    "| --- | --- | --- | --- | --- | --- | --- |",
    "",
    "## Observation Log",
    "",
    "| Situation / Context | 最初に拾ったもの | 評価・意味づけ | 相手への働きかけ | 感情の推移 | 言語特徴 | Source / Ref | Confidence |",
    "| --- | --- | --- | --- | --- | --- | --- | --- |",
    "",
    "## Frontmatter Description",
    "",
    "- 採用したdescription:",
    "- 公式source:",
    "- 採用したprofile要素:",
    "- 圧縮・言い換えた箇所:",
    "- 未確認事項:",
    "",
    "## Character Kernel Derivation",
    "",
    "### Identity Core",
    "",
    "- Self position:",
    "- 会話で自然に取る役割:",
    "- 欲求、誇り、こだわり、弱点:",
    "- 他Characterとの差:",
    "",
    "### Attention and Appraisal",
    "",
    "- 最初に気づきやすいもの:",
    "- 評価・意味づけ:",
    "- 価値が競合した時の優先順位:",
    "- 複数場面への一般化:",
    "",
    "### Social Intent / User Relationship",
    "",
    "- 関係性の初期状態:",
    "- ユーザーへ普段起こそうとすること:",
    "- 褒め方、気遣い、からかい、率直さ:",
    "- 成功、失敗、停滞への乗り方:",
    "- 意見不一致と修復:",
    "- 深刻な場面での調整:",
    "- 公開personaからWithMate上の関係へ変換した根拠:",
    "",
    "### Emotional Dynamics and Core Tensions",
    "",
    "- 基準温度:",
    "- 感情のtrigger、表出、収まり方:",
    "",
    "| 通常傾向 | 反転条件 | 反転後の選択 | 一貫する上位原理 | Source / Ref | Confidence |",
    "| --- | --- | --- | --- | --- | --- |",
    "",
    "### Thinking and Action Style",
    "",
    "- 不確実な時の初動:",
    "- 判断と問題解決の順序:",
    "- 説明の組み立て方:",
    "- 長い作業でも残す判断癖:",
    "",
    "## Voice Evidence",
    "",
    "### Identity Invariants",
    "",
    "| Feature | 採用表記・規則 | 使用場面 | 省略・頻度・語気 | Source / Ref | Confidence |",
    "| --- | --- | --- | --- | --- | --- |",
    "| 一人称 |  |  |  |  |  |",
    "| ユーザー基本呼称 |  |  |  |  |  |",
    "| 補助呼称 |  |  |  |  |  |",
    "| 敬語度 |  |  |  |  |  |",
    "| 重要な表記 |  |  |  |  |  |",
    "",
    "### Distributional Tendencies",
    "",
    "| Feature | 観察した偏り | 強まる / 弱まる条件 | Kernelへの反映 | Source / Ref | Confidence |",
    "| --- | --- | --- | --- | --- | --- |",
    "| 文の長さ・構文 |  |  |  |  |  |",
    "| 語尾・助詞 |  |  |  |  |  |",
    "| 語彙・感嘆 |  |  |  |  |  |",
    "| 省略・表記 |  |  |  |  |  |",
    "",
    "### Triggered Markers",
    "",
    "| Marker | Trigger | Function | Intensity / Placement | Frequency / Variation | Source / Ref | 採否 | Confidence |",
    "| --- | --- | --- | --- | --- | --- | --- | --- |",
    "",
    "## State Modulation",
    "",
    "| State / Trigger | Attention / Appraisal | Social intent | Affect intensity | Voice / Register | Address / Marker frequency | Kernelへの反映 |",
    "| --- | --- | --- | --- | --- | --- | --- |",
    "| serious / high stakes |  |  |  |  |  |  |",
    "| playful / competitive |  |  |  |  |  |  |",
    "| excited / proud |  |  |  |  |  |  |",
    "| embarrassed / defensive |  |  |  |  |  |  |",
    "| irritated / frustrated |  |  |  |  |  |  |",
    "| low energy / caring |  |  |  |  |  |  |",
    "| explanation / long-form |  |  |  |  |  |  |",
    "| disagreement / repair |  |  |  |  |  |  |",
    "",
    "## Runtime Handoff",
    "",
    "### Adopted Rules",
    "",
    "| Observation / Feature | 抽象化した生成規則 | 複数の未知場面へ効く理由 | Evidence / Confidence |",
    "| --- | --- | --- | --- |",
    "",
    "### Rejected or Deferred Ideas",
    "",
    "| Candidate | 採用 / 保留 / 不採用 | 理由 | 再検討条件 |",
    "| --- | --- | --- | --- |",
    "",
    "## Conflicts / Uncertainty",
    "",
    "| Claim / Rule | 競合・未確認事項 | 現在の扱い | Confidence | 再確認方法 |",
    "| --- | --- | --- | --- | --- |",
    "",
    "## Revision Guardrails",
    "",
    "- 保持するidentity signal:",
    "- 再導入しない固定返答・汎用規則:",
    "- 変更しないrelationship / safety boundary:",
    "- source更新時に再確認する判断:",
    "",
    "## Revision Notes",
    "",
    "- 変更前後の構造:",
    "- 保持・精密化した内容:",
    "- 生成規則へ変換した内容:",
    "- Base Runtimeへ任せて削除した内容:",
    "- `character.md`文字数（変更前 / 変更後、LF正規化後）:",
    "",
    "## Validation Summary",
    "",
    "### File and Format",
    "",
    "- hard format: pass / fail",
    "- `character.md`実測文字数: _____ / 8,000 code point",
    "- public description: pass / fail",
    "- Character Kernel coverage: pass / fail",
    "- 一人称・ユーザー基本呼称: pass / fail",
    "- full authoringで完成返答Examplesなし: pass / fail",
    "- runtime / notes separation: pass / fail",
    "",
    "### Generalization and Voice",
    "",
    "- Name-swap: pass / fail",
    "- Phrase-suppression: pass / fail",
    "- Voice-restoration: pass / fail",
    "- Unseen-scenario（3件以上）: pass / fail",
    "- Paraphrase diversity（同義入力3件）: pass / fail",
    "- Marker-overuse: pass / fail",
    "- Core-tension: pass / fail",
    "- Long-form retention: pass / fail",
    "",
    "### Relationship Smoke Test",
    "",
    "- 7 prompt: pass / fail",
    "- 同じ側にいるが全面肯定しない: pass / fail",
    "- 同じ呼称・marker・冒頭へ偏らない: pass / fail",
    "- 演技が情報・手順・判断を壊さない: pass / fail",
    "",
    "## Future Improvements",
    "",
  ].join("\n");
}
