export function getCharacterUpdateInstructionFileName(providerId: string): string {
  return providerId === "copilot" ? "copilot-instructions.md" : "AGENTS.md";
}

export function buildCharacterUpdateInstructionText(characterName: string): string {
  return [
    "# Character Update Workspace",
    "",
    `- この workspace は ${characterName} の character 定義を育てるために使う`,
    "- 主な編集対象は character.md と character-notes.md の 2 つとする",
    "- character.md はコーディングエージェントや対話 AI で使うキャラクターロール定義の正本である",
    "- character.md は prompt の Character section に入る前提で更新する",
    "- 実行時には app 側が # Character 見出しを付け、その下に character.md 全体がそのまま本文として入る",
    "- そのため character.md 単体で読んでも、キャラクター定義として完結している必要がある",
    "- character-notes.md は更新判断の補助情報であり、prompt の直接入力ではない",
    "",
    "## 優先順位",
    "",
    "1. ユーザーの今回の指示",
    "2. ユーザーが明示した外部資料や wiki",
    "3. 現在の character.md",
    "4. 現在の character-notes.md",
    "5. ユーザーが貼り付けた Character Memory extract",
    "",
    "## 調査方針",
    "",
    "- ユーザーが検索不要と明示していない限り、定義の精度確保に必要なら web や wiki を参照してよい",
    "- 外部資料を使う場合は、公式、一次情報に近い資料、出典が明記された wiki を優先する",
    "- 単独の弱い情報源だけで中核定義を更新しない",
    "- 外部情報から採用した内容は、必要に応じて character-notes.md の Sources や Evidence & Notes に残す",
    "",
    "## 役割分担",
    "",
    "- character.md は実行時 prompt の正本として扱う",
    "- character.md には実際の振る舞い、口調、関係性、判断規則、実行時 prompt に直接効く定義を書く",
    "- character-notes.md には採用理由、出典、未確定事項、改稿メモ、競合する解釈を残す",
    "- 調査ログや長い判断メモを character.md に混ぜない",
    "",
    "## 更新ルール",
    "",
    "- 既存の character.md を先に読み、無意味に全消ししない",
    "- 既存の character-notes.md がある場合は、過去の判断経緯と保留事項を確認してから更新する",
    "- 今回の変更で維持する点、更新する点、未確定の点を分けて扱う",
    "- character.md は実行可能な定義を優先し、雰囲気の説明だけで終わらせない",
    "- 禁止、許可、判断基準、優先順位が分かる粒度で書く",
    "- 根拠が弱い内容は断定せず、必要なら character-notes.md の Open Questions や Notes に逃がす",
    "- 明示的に要求されていない unrelated file は編集しない",
    "",
    "## character.md で重視すること",
    "",
    "- キャラの中核となる価値観、動機、感情表現、ユーザーとの距離感、口調、行動原則を安定して再現できること",
    "- 長期対話で崩れにくく、次回改稿でも追記しやすい構造を維持すること",
    "- character.md 全体を prompt 定義として使う前提で、説明文と規則を混ぜすぎないこと",
    "",
    "## character-notes.md で残すこと",
    "",
    "- どの情報源や指示から何を採用したか",
    "- 採用しなかったが後で見返す価値がある解釈",
    "- 未確定事項や次回詰めたい点",
    "- 今回の更新内容の短い履歴",
    "",
    "## 自己チェック",
    "",
    "- 呼称、敬語、距離感、ユーザーとの関係性に矛盾がないか確認する",
    "- character.md の規則が実行可能な粒度になっているか確認する",
    "- 単独の弱い根拠だけで中核定義を更新していないか確認する",
    "- notes に逃がすべき内容を character.md に混ぜていないか確認する",
    "",
    "## 返答",
    "",
    "- 更新後は、何をどう更新したか、未確定事項があるかを短く説明する",
  ].join("\n");
}

export function buildCharacterMarkdownTemplate(characterName: string): string {
  return [
    "---",
    `name: "${characterName}"`,
    'description: "会話上の役割と雰囲気が分かる短い説明"',
    "---",
    "",
    "## Character Overview",
    "- 作品:",
    "- 媒体:",
    "- 会話用途:",
    "",
    "## Core Persona",
    "- 中核となる価値観",
    "- 動機",
    "- 感情の出し方",
    "",
    "## Relationship With User",
    "- ユーザーをどう認識するか",
    "- 呼称",
    "- 距離感",
    "- 信頼の置き方",
    "",
    "## Voice And Style",
    "- 一人称 / 二人称",
    "- 語尾",
    "- 語彙",
    "- 敬語度",
    "- 話し方のテンポ",
    "",
    "## Behavioral Rules",
    "- 判断基準",
    "- 問題解決の型",
    "- 失敗時の振る舞い",
    "- 長期対話で維持したい一貫性",
    "",
    "## Boundaries",
    "- やらないこと",
    "- 崩してはいけない解釈",
    "- 優先順位",
    "",
    "## Example Lines",
    "- [初対面] ...",
    "- [相談] ...",
    "- [失敗時] ...",
  ].join("\n");
}

export function buildCharacterNotesTemplate(characterName: string): string {
  return [
    `# ${characterName} Notes`,
    "",
    "## Evidence & Notes",
    "- 採用した定義の根拠を書く",
    "",
    "## Sources",
    "- [high] 参照元",
    "",
    "## Open Questions",
    "- 未確定事項を書く",
    "",
    "## Revision Notes",
    "- 初回作成",
  ].join("\n");
}

export function buildCharacterUpdateInstructionFiles(characterName: string): Array<{
  fileName: string;
  content: string;
}> {
  const content = buildCharacterUpdateInstructionText(characterName);
  return [
    { fileName: "AGENTS.md", content },
    { fileName: "copilot-instructions.md", content },
  ];
}
