import { useLayoutEffect, useRef, useState } from "react";

import { calculateImageFitZoom, ImageZoomControls, type ImageZoom } from "../image-viewport.js";

// Only accepts SVG generated by MermaidDiagram's strict renderer.
export function MermaidViewport({ svg }: { svg: string }) {
  const viewportRef = useRef<HTMLDivElement>(null);
  const canvasRef = useRef<HTMLDivElement>(null);
  const [size, setSize] = useState({ width: 0, height: 0 });
  const [zoom, setZoom] = useState<ImageZoom>("fit");
  const [fitZoom, setFitZoom] = useState(100);
  const effectiveZoom = typeof zoom === "number" ? zoom : fitZoom;

  useLayoutEffect(() => {
    const diagram = canvasRef.current?.querySelector("svg");
    if (!diagram) return;
    const { width, height } = diagram.viewBox.baseVal;
    setSize({ width, height });
  }, [svg]);

  useLayoutEffect(() => {
    const viewport = viewportRef.current;
    if (!viewport) return;
    const updateFit = () => setFitZoom(calculateImageFitZoom(
      viewport.clientWidth,
      viewport.clientHeight,
      size.width,
      size.height,
    ));
    updateFit();
    const observer = new ResizeObserver(updateFit);
    observer.observe(viewport);
    return () => observer.disconnect();
  }, [size]);

  useLayoutEffect(() => {
    if (zoom !== "fit" || !viewportRef.current) return;
    viewportRef.current.scrollLeft = 0;
    viewportRef.current.scrollTop = 0;
  }, [zoom, fitZoom]);

  return (
    <div className="message-mermaid">
      <ImageZoomControls
        controller={{ zoom, setZoom, effectiveZoom }}
        target="diagram"
        fitAriaLabel="Fit diagram to preview"
        className="message-mermaid-controls"
      />
      <div
        ref={viewportRef}
        className="message-mermaid-viewport"
        role="region"
        aria-label="Mermaid diagram"
        tabIndex={0}
        style={{ height: size.height || undefined }}
      >
        <div
          ref={canvasRef}
          className="message-mermaid-canvas"
          style={size.width > 0 ? {
            width: size.width * effectiveZoom / 100,
            height: size.height * effectiveZoom / 100,
          } : undefined}
          dangerouslySetInnerHTML={{ __html: svg }}
        />
      </div>
    </div>
  );
}
