import { useLayoutEffect, useMemo, useRef, useState, type MouseEvent } from "react";

import { calculateImageFitZoom, ImageZoomControls, useCtrlWheelZoom, type ImageZoom } from "../image-viewport.js";
import { useViewportPan } from "../viewport-pan.js";
import { isAllowedMarkdownHref, openMarkdownLink } from "./markdown-links.js";

// Only accepts SVG generated by MermaidDiagram's strict renderer.
export function MermaidViewport({
  svg,
  onOpenPath,
}: {
  svg: string;
  onOpenPath?: (target: string) => void;
}) {
  const viewportRef = useRef<HTMLDivElement>(null);
  const canvasRef = useRef<HTMLDivElement>(null);
  const diagramHtml = useMemo(() => ({ __html: svg }), [svg]);
  const [size, setSize] = useState({ width: 0, height: 0 });
  const [zoom, setZoom] = useState<ImageZoom>("fit");
  const [fitZoom, setFitZoom] = useState(100);
  const [linkError, setLinkError] = useState("");
  const suppressLinkClickRef = useRef(false);
  const effectiveZoom = typeof zoom === "number" ? zoom : fitZoom;
  const pan = useViewportPan(svg);
  useCtrlWheelZoom(viewportRef, fitZoom, setZoom);

  const handleLinkClick = (event: MouseEvent<HTMLDivElement>) => {
    const suppressClick = suppressLinkClickRef.current;
    suppressLinkClickRef.current = false;
    const link = (event.target as Element).closest?.("a");
    if (!link || !event.currentTarget.contains(link) || event.defaultPrevented) return;
    // SVG anchors must never navigate the Electron document, including auxiliary clicks.
    event.preventDefault();
    if (event.button !== 0 || suppressClick) return;
    const target = (link.getAttribute("href") ?? link.getAttribute("xlink:href") ?? "").trim();
    if (!target || !isAllowedMarkdownHref(target)) {
      setLinkError("This diagram link has no supported destination.");
      return;
    }
    setLinkError("");
    if (target.startsWith("#")) return;
    openMarkdownLink(target.startsWith("//") ? `https:${target}` : target, onOpenPath);
  };

  useLayoutEffect(() => {
    const diagram = canvasRef.current?.querySelector("svg");
    if (!diagram) return;
    const { width, height } = diagram.viewBox.baseVal;
    setSize({ width, height });
  }, [svg]);

  useLayoutEffect(() => {
    const viewport = viewportRef.current;
    if (!viewport) return;
    const updateFit = () => setFitZoom(calculateImageFitZoom(
      viewport.clientWidth,
      viewport.clientHeight,
      size.width,
      size.height,
    ));
    updateFit();
    const observer = new ResizeObserver(updateFit);
    observer.observe(viewport);
    return () => observer.disconnect();
  }, [size]);

  useLayoutEffect(() => {
    if (zoom !== "fit" || !viewportRef.current) return;
    viewportRef.current.scrollLeft = 0;
    viewportRef.current.scrollTop = 0;
  }, [zoom, fitZoom]);

  return (
    <div className="message-mermaid">
      <ImageZoomControls
        controller={{ zoom, setZoom, effectiveZoom }}
        target="diagram"
        fitAriaLabel="Fit diagram to preview"
        className="message-mermaid-controls"
      />
      <div
        ref={viewportRef}
        className={`message-mermaid-viewport${pan.isPanning ? " is-panning" : ""}`}
        onPointerDown={(event) => {
          pan.startPan(event);
          suppressLinkClickRef.current = event.defaultPrevented;
        }}
        onPointerMove={pan.movePan}
        onPointerUp={pan.stopPan}
        onPointerCancel={pan.stopPan}
        onLostPointerCapture={pan.handlePanCaptureLoss}
        onClick={handleLinkClick}
        onAuxClick={handleLinkClick}
        title="Ctrl + left-drag to pan"
        role="region"
        aria-label="Mermaid diagram"
        tabIndex={0}
        style={{ height: size.height || undefined }}
      >
        <div
          ref={canvasRef}
          className="message-mermaid-canvas"
          style={size.width > 0 ? {
            width: size.width * effectiveZoom / 100,
            height: size.height * effectiveZoom / 100,
          } : undefined}
          dangerouslySetInnerHTML={diagramHtml}
        />
      </div>
      {linkError ? <p className="message-mermaid-error" role="alert">{linkError}</p> : null}
    </div>
  );
}
